In [46]:
import numpy as np 

array = np.array([1, 2, 3])
print( "Type :",type(array))          

print("Shape :",array.shape)        

print("Elements :",array[0], array[1], array[2])   

array[0] = 5               
print("Modified array :",array)              


Type : <class 'numpy.ndarray'>
Shape : (3,)
Elements : 1 2 3
Modified array : [5 2 3]


In [47]:
array = np.array([[1,2,3],
                  [4,5,6]])  
  
print("Shape :",array.shape)   
                
print("Elements :",array[0, 0], array[0, 1], array[1, 0])

Shape : (2, 3)
Elements : 1 2 4


In [48]:
zeros_array = np.zeros((5,6))  
print(zeros_array)     

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [49]:
one_array = np.ones((5,3))  
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
random_array = np.random.random((5,5))
print(random_array)

[[0.62449246 0.77549351 0.05544084 0.7788905  0.32529261]
 [0.761102   0.03815773 0.57166359 0.99053403 0.99625309]
 [0.63421795 0.15326779 0.34095768 0.19016373 0.54756159]
 [0.4545997  0.0684104  0.49326514 0.25680402 0.94243642]
 [0.47154409 0.90500578 0.44286983 0.47663124 0.86645886]]


In [51]:
three_dimensional_array = np.array([[1,2,3],
                                    [4,5,6],
                                    [7,8,9]],)
print(three_dimensional_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x = np.array([1.5, 2.6])

print(x.dtype) 

y = np.array([1, 2])
print(y.dtype)

z = np.array(["Abu", "adhshjdhjajkadh"])
print(z.dtype)

float64
int64
<U15
